# Generated by Django 6.0 on 2026-06-26 11:14

import catering.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('catering', '0001_initial'), ('catering', '0002_cateringevent_staffmember'), ('catering', '0003_member_memberlog_delete_staffmember'), ('catering', '0004_cateringevent_alternate_phone_and_more'), ('catering', '0005_cateringevent_menu_items'), ('catering', '0006_category_gujarati_name'), ('catering', '0007_rename_name_menu_item_name_remove_menu_item_descp_and_more'), ('catering', '0008_menu'), ('catering', '0009_menu_price_per_plate'), ('catering', '0010_rename_alternate_phone_cateringevent_contact_number'), ('catering', '0011_alter_category_options_category_order'), ('catering', '0012_menu_note'), ('catering', '0013_booking'), ('catering', '0014_cateringevent_advance_amount_cateringevent_rate_and_more'), ('catering', '0015_alter_user_profile_image'), ('catering', '0016_alter_user_phone_number'), ('catering', '0017_cateringevent_assigned_manager_and_more'), ('catering', '0018_alter_user_managers'), ('catering', '0019_alter_galleryitem_image'), ('catering', '0020_menu_created_by_adminnote'), ('catering', '0021_alter_adminnote_options_adminnote_note_date'), ('catering', '0022_pdflog'), ('catering', '0023_activitylog'), ('catering', '0024_activitylog_related_date_activitylog_related_id_and_more'), ('catering', '0025_add_custom_items_text_to_menu'), ('catering', '0026_add_is_approved_to_event_and_menu'), ('catering', '0027_booking_name_gu_booking_venue_gu_and_more')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('gujarati_name', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first (e.g. 1, 2, 3)')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('profile_image', models.ImageField(blank=True, default='profile_images/default_user.png', upload_to='profile_images/')),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('manager', 'Manager'), ('admin', 'Admin')], default='customer', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', catering.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Menu_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catering.category')),
                ('description', models.TextField(blank=True, null=True)),
                ('gujarati_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('tags', models.CharField(blank=True, default='', help_text='Comma-separated tags e.g. wedding,starter,paneer', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CateringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('guests', models.IntegerField()),
                ('event_type', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='received', max_length=20)),
                ('venue', models.CharField(default='Not Specified', max_length=200)),
                ('menu_items', models.ManyToManyField(blank=True, related_name='events', to='catering.menu_item')),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Rate per plate for this event', max_digits=10)),
                ('staff_count', models.IntegerField(default=0, help_text='Number of staff assigned')),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_events', to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('event_city', models.CharField(blank=True, default='', max_length=100)),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('notes_updated_at', models.DateTimeField(blank=True, null=True)),
                ('notes_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_notes', to=settings.AUTH_USER_MODEL)),
                ('tracking_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('description_gu', models.TextField(blank=True, default='', help_text='Notes in Gujarati')),
                ('title_gu', models.CharField(blank=True, default='', help_text='Client name in Gujarati', max_length=200)),
                ('venue_gu', models.CharField(blank=True, default='', help_text='Venue in Gujarati', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('default_rate', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MemberLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=200)),
                ('staff_count', models.IntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_given', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entry_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='catering.member')),
            ],
        ),
        migrations.CreateModel(
            name='EventStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('head_chef', 'Head Chef'), ('sous_chef', 'Sous Chef'), ('server', 'Server'), ('coordinator', 'Coordinator'), ('driver', 'Driver')], default='server', max_length=20)),
                ('confirmed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='catering.cateringevent')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Event Staff',
                'unique_together': {('event', 'member')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=10)),
                ('arrived_at', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('event_staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='catering.eventstaff')),
            ],
            options={
                'verbose_name_plural': 'Attendance Records',
            },
        ),
        migrations.CreateModel(
            name='MenuItemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_count', models.IntegerField(default=0)),
                ('profit_margin_pct', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('seasonal_peak', models.CharField(blank=True, default='', help_text='Comma-separated month numbers, e.g. "11,12,1,2"', max_length=50)),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='catering.menu_item')),
            ],
            options={
                'verbose_name_plural': 'Menu Item Stats',
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('deadline', models.DateField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['deadline', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_new_ip', models.BooleanField(default=False)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Login Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('3day', '3 Days Before'), ('1day', '1 Day Before')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='catering.cateringevent')),
            ],
            options={
                'unique_together': {('event', 'reminder_type')},
            },
        ),
        migrations.CreateModel(
            name='ItemCoOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('item_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooccurrence_a', to='catering.menu_item')),
                ('item_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooccurrence_b', to='catering.menu_item')),
            ],
            options={
                'verbose_name_plural': 'Item Co-Occurrences',
                'unique_together': {('item_a', 'item_b')},
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('wedding', 'Wedding'), ('corporate', 'Corporate'), ('birthday', 'Birthday'), ('food', 'Food'), ('setup', 'Setup'), ('other', 'Other')], default='other', max_length=50)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('cloudinary_url', models.URLField(blank=True, default='', max_length=500)),
                ('youtube_url', models.URLField(blank=True, default='', max_length=500)),
                ('image', models.FileField(blank=True, null=True, upload_to='gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('note_type', models.CharField(choices=[('general', 'General'), ('event', 'Event Note'), ('tracker', 'Tracker Note')], default='general', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notes', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notes', to='catering.cateringevent')),
                ('note_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-note_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PdfLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_details', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('related_date', models.DateField(blank=True, null=True)),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('related_type', models.CharField(blank=True, choices=[('event', 'Event'), ('menu', 'Menu'), ('booking', 'Booking'), ('other', 'Other')], default='other', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='catering.cateringevent')),
                ('items', models.ManyToManyField(blank=True, to='catering.menu_item')),
                ('price_per_plate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
                ('custom_items_text', models.TextField(blank=True, default='')),
                ('is_approved', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(max_length=50)),
                ('guest_count', models.IntegerField()),
                ('meal_time', models.CharField(blank=True, max_length=50, null=True)),
                ('package_type', models.CharField(max_length=100)),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name_gu', models.CharField(blank=True, default='', help_text='Customer name in Gujarati', max_length=100)),
                ('venue_gu', models.CharField(blank=True, default='', help_text='Venue in Gujarati', max_length=200)),
            ],
        ),
    ]
