# Generated by Django 6.0 on 2026-01-02 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0007_rename_name_menu_item_name_remove_menu_item_descp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='catering.cateringevent')),
                ('items', models.ManyToManyField(blank=True, to='catering.menu_item')),
            ],
        ),
    ]
