# Generated by Django 6.0 on 2026-01-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0008_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='price_per_plate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
