# Generated by Django 6.0 on 2026-01-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0009_menu_price_per_plate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cateringevent',
            old_name='alternate_phone',
            new_name='contact_number',
        ),
    ]
