# Generated by Django 6.0 on 2026-01-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0010_rename_alternate_phone_cateringevent_contact_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first (e.g. 1, 2, 3)'),
        ),
    ]
