# Generated by Django 6.0 on 2026-01-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0011_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
