# Generated by Django 6.0 on 2026-01-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0012_menu_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(max_length=50)),
                ('guest_count', models.IntegerField()),
                ('meal_time', models.CharField(blank=True, max_length=50, null=True)),
                ('package_type', models.CharField(max_length=100)),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
