# Generated by Django 6.0 on 2026-01-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0013_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringevent',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cateringevent',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Rate per plate for this event', max_digits=10),
        ),
        migrations.AddField(
            model_name='cateringevent',
            name='staff_count',
            field=models.IntegerField(default=0, help_text='Number of staff assigned'),
        ),
    ]
