# Generated by Django 6.0 on 2026-05-27 13:46

import catering.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0017_cateringevent_assigned_manager_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', catering.models.CustomUserManager()),
            ],
        ),
    ]
