# Generated by Django 6.0 on 2026-05-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0018_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
