# Generated by Django 6.0 on 2026-05-27 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0019_alter_galleryitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='AdminNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('note_type', models.CharField(choices=[('general', 'General'), ('event', 'Event Note'), ('tracker', 'Tracker Note')], default='general', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notes', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notes', to='catering.cateringevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
