# Generated by Django 6.0 on 2026-05-27 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0020_menu_created_by_adminnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminnote',
            options={'ordering': ['-note_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='adminnote',
            name='note_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
