# Generated by Django 6.0 on 2026-05-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0025_add_custom_items_text_to_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringevent',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
