# Generated by Django 6.0 on 2026-06-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0026_add_is_approved_to_event_and_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name_gu',
            field=models.CharField(blank=True, default='', help_text='Customer name in Gujarati', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='venue_gu',
            field=models.CharField(blank=True, default='', help_text='Venue in Gujarati', max_length=200),
        ),
        migrations.AddField(
            model_name='cateringevent',
            name='description_gu',
            field=models.TextField(blank=True, default='', help_text='Notes in Gujarati'),
        ),
        migrations.AddField(
            model_name='cateringevent',
            name='title_gu',
            field=models.CharField(blank=True, default='', help_text='Client name in Gujarati', max_length=200),
        ),
        migrations.AddField(
            model_name='cateringevent',
            name='venue_gu',
            field=models.CharField(blank=True, default='', help_text='Venue in Gujarati', max_length=200),
        ),
    ]
