# Generated by Django 6.0 on 2026-07-06 16:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


def gen_unique_review_tokens(apps, schema_editor):
    """Generate unique review_token UUIDs for all existing CateringEvent rows."""
    CateringEvent = apps.get_model('catering', 'CateringEvent')
    for event in CateringEvent.objects.all():
        event.review_token = uuid.uuid4()
        event.save(update_fields=['review_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0001_squashed_0027_booking_name_gu_booking_venue_gu_and_more'),
    ]

    operations = [
        # Step 1: Add the field WITHOUT unique constraint
        migrations.AddField(
            model_name='cateringevent',
            name='review_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token for public review link'),
        ),
        # Step 2: Generate unique UUIDs for all existing rows
        migrations.RunPython(gen_unique_review_tokens, migrations.RunPython.noop),
        # Step 3: Now add the unique constraint
        migrations.AlterField(
            model_name='cateringevent',
            name='review_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token for public review link', unique=True),
        ),
        # Step 4: Create Review model
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1-5 star rating')),
                ('review_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='catering.cateringevent')),
            ],
        ),
    ]
