# Generated by Django 6.0 on 2026-07-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0029_review_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('subtitle', models.CharField(help_text='e.g. Mother of the Bride, NRI Client', max_length=150)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
