# Generated by Django 6.0 on 2026-07-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0030_sampletestimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='admin_response',
            field=models.TextField(blank=True, default='', help_text='Admin reply to the review'),
        ),
        migrations.AddField(
            model_name='review',
            name='email_notified',
            field=models.BooleanField(default=False, help_text='Admin was emailed about this review'),
        ),
        migrations.AddField(
            model_name='review',
            name='response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
