# Generated by Django 6.0 on 2026-07-08 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0031_review_admin_response_review_email_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringevent',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Whether the bill has been fully paid'),
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('label', models.CharField(blank=True, default='', help_text='e.g. Day 1 - Haldi, Day 2 - Wedding', max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_dates', to='catering.cateringevent')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('event', 'date')},
            },
        ),
    ]
