# Generated by Django 6.0 on 2026-07-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0032_cateringevent_is_paid_eventdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringevent',
            name='miscellaneous_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cateringevent',
            name='miscellaneous_reason',
            field=models.CharField(blank=True, help_text='Reason for miscellaneous charges', max_length=200, null=True),
        ),
    ]
