# Generated by Django 6.0 on 2026-07-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0033_cateringevent_miscellaneous_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='guest_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cateringevent',
            name='guests',
            field=models.IntegerField(default=0),
        ),
    ]
