const menuData_EN = [
    {
  category: "Welcome Drinks",
  icon: "🍹",
  items: [
    "Black Grape Orange",
    "Black Grape Pineapple",
    "Bombay Boom",
    "Cocktail Juice",
    "Cold Coffee",
    "Coconut Water",
    "Dadam Darbari",
    "Film City",
    "Fruit Dish",
    "Fruit Punch",
    "Green Grape Pineapple",
    "Green Magic",
    "Guava Juice",
    "Ice Tea",
    "Jalpari",
    "Kabul (Black Grape Lychee)",
    "Kiwi Lychee Cooler",
    "Lemon Mint Mojito",
    "Lemon Sharbat",
    "Lychee Limca",
    "Orange Blossom",
    "Orange Juice",
    "Orange Strawberry Juice",
    "Pina Colada",
    "Pineapple Black Grape",
    "Pineapple Juice",
    "Pineapple Kiwi",
    "Pineapple Lemon Juice",
    "Pineapple Mosambi Juice",
    "Pineapple Shake",
    "Pineapple Strawberry Pulp",
    "Pomegranate Punch",
    "Shimran",
    "Shot Counter",
    "Strawberry Juice",
    "Strawberry Shake",
    "Sugarcane Juice",
    "Variyali Sharbat",
    "Watermelon Falsa",
    "Watermelon Juice"
  ]
},
{
  category: "Biting",
  icon: "🥟",
  items: [
    "Aloo Tikki",
    "Cheese Balls",
    "Cheese Corn Balls",
    "Cheese Corn Potli",
    "Cheese Paneer Balls",
    "Cocktail Samosa",
    "Corn Kebab",
    "Corn Tikki",
    "Hara Bhara Cheese Kebab",
    "Hara Bhara Kebab",
    "Hari Bhari Tikki",
    "Hummus Falafel Tikki",
    "Hyderabadi Tikki",
    "Italian Volvo",
    "Jalapeno Cheese Balls",
    "Mexican Tikki with Salsa",
    "Mini Spring Roll",
    "Paneer Cheese Lifafa",
    "Paneer Chili Dry",
    "Paneer Hazari Tikka",
    "Paneer Satay",
    "Roasted Paneer",
    "Sesame Paneer Finger",
    "Spinach Paneer Rolls",
    "Stick Lollipop",
    "Thai Corn Fritters",
    "Veg Lollipop"
  ]
},
    {
  category: "Soups",
  icon: "🥣",
  items: [
    "Carrot Soup",
    "Chili Bean Soup",
    "Coriander Soup",
    "Cream Black Tomato Soup",
    "Cream of Broccoli Almond Soup",
    "Dal-Feni Soup",
    "Garlic Ginger Soup",
    "Hot & Sour Soup",
    "Italian Tomato Soup",
    "Lemon Coriander Soup",
    "Masala Soup",
    "Mediterranean Green Veg Soup",
    "Mexican Chili Bean Soup",
    "Mexican Nachos Soup",
    "Mexican Tortilla Soup",
    "Minestrone Soup",
    "Nathna Soup",
    "Roman Soup",
    "Salsa Bean Soup",
    "Sweet Corn Soup",
    "Sweet Corn Veg Soup",
    "Thai Bean Soup",
    "Tomato Basil Soup",
    "Tomato Corn Cheese Soup",
    "Tomato Moroccan Soup",
    "Tomato Soup",
    "Varadiyu Soup",
    "Veg Garlic Soup",
    "Veg Manchurian Soup",
    "Vegetable Soup"
  ]
},
    {
    category: "Starters",
    icon: "🥟",
    items: [
        "Aloo Chatpata",
        "Aloo Tikki",
        "Cheese Balls",
        "Cheese Corn Balls",
        "Cheese Corn Potli",
        "Cheese Paneer Balls",
        "Cheese Samosa",
        "Chili Potato",
        "Chinese Cigars",
        "Corn Kebab",
        "Corn Tikki",
        "Coriander Kali",
        "Dragon Potato",
        "Dry Manchurian",
        "Garlic Toast",
        "Hara Bhara Cheese Kebab",
        "Hara Bhara Kebab",
        "Hari Bhari Tikki",
        "Hyderabadi Tikki",
        "Hummus Falafel Tikki",
        "Italian Buns",
        "Italian Volvo",
        "Jalapeno Cheese Balls",
        "Mexican Tikki with Salsa",
        "Mini Spring Roll",
        "Paneer Barbecue",
        "Paneer Cheese Lifafa",
        "Paneer Chili Dry",
        "Paneer Hazari Tikka",
        "Paneer Satay",
        "Paneer Tikka (Roasted)",
        "Pesto Sauce",
        "Roasted Paneer",
        "Sesame Paneer Finger",
        "Sesame Toss",
        "Spinach Paneer Rolls",
        "Stick Lollipop",
        "Thai Corn Fritters",
        "Veg Barbecue",
        "Veg Crispy",
        "Veg Lollipop",
        "Veg Potato" 
    ]
    },
{
  category: "Pure Ghee Sweets",
  icon: "🍨",
  items: [
    "Adadiya Gundipak",
    "Cashew Adadiya",
    "Cashew Mesub",
    "Churma Ladoo",
    "Dry Fruit Gundi",
    "Fada Lapsi",
    "Jalebi",
    "Jambu",
    "Kala Jam",
    "Kheer",
    "Lapsi",
    "Lisa Ladoo",
    "Magaj Ladoo",
    "Magdi Ladoo",
    "Mesub",
    "Mohanthal",
    "Mohanthal Lachko",
    "Moong Dal Sheera",
    "Puran Poli",
    "Rava Ladoo",
    "Rava Sheera",
    "Saffron Almond Adadiya",
    "Saffron Pistachio Adadiya",
    "Sukhdi"  
  ]
},
{
  category: "Special Liquid Sweets",
  icon: "🍧",
  items: [
    "Alfred Plaza",
    "Basundi",
    "Cream Kesar Thandai",
    "Cream Pine Nut Chikki",
    "Cream Pine Shahi",
    "Custard Apple Dry Fruit Basundi",
    "Dry Fruit Apple Plaza",
    "Dry Fruit Black Currant Plaza",
    "Dry Fruit Butter Laccha Rabdi",
    "Dry Fruit Butter Plaza",
    "Dry Fruit Cream Fruit Salad",
    "Dry Fruit Kalkati Plaza",
    "Dry Fruit Kesar Laccha Rabdi",
    "Dry Fruit Lychee Laccha Rabdi",
    "Dry Fruit Lychee Plaza",
    "Dry Fruit Mango Pi",
    "Dry Fruit Pineapple Chili",
    "Dryfruit Sitafal Basundi",
    "Ghevar Cashew Rabdi",
    "Kings & Honey Laccha Rabdi",
    "Kesar Dry Fruit Basundi",
    "Kesar Dry Fruit Ras Madhuri",
    "Pine Coconut Rabdi",
    "Rajbhog Plaza",
    "Strawberry Plaza",
    "White Ras Madhuri"
  ]
},
{
  category: "Hot Halwa & Shrikhand",
  icon: "🥮",
  items: [
    "Anjeer Almond Halwa",
    "Anjeer Kasturi Halwa",
    "Butterscotch Halwa",
    "Cookies & Cream Matka",
    "Dry Anjeer Halwa",
    "Dry Carrot Halwa",
    "Dry Dates Halwa",
    "Dry Dudhi Halwa",
    "Dry Thabdi Halwa",
    "Dry Walnut Halwa",
    "Fruit Shrikhand",
    "Green Coconut Halwa",
    "Green Ginger Halwa",
    "Kesar Kewari Halwa",
    "Kesar Malai Matka",
    "Kesar Shrikhand",
    "Malai Baati",
    "Mango Matka",
    "Mango Mattho",
    "Mango Shrikhand",
    "Mix Slice Halwa",
    "Mawa Malai Matka",
    "Pancharatna Halwa",
    "Pineapple Chili Halwa",
    "Pineapple Chili Shrikhand",
    "Pineapple Matka",
    "Pineapple Mattho",
    "Raspberry Matka",
    "Silver Slice",
    "Vanilla Matka",
    "White Shrikhand"
  ]
},
{
  category: "Indian Breads (Roti)",
  icon: "🫓",
  items: [
    "Baby Naan",
    "Baby Paratha",
    "Bhature",
    "Biscuit Roti",
    "Bread Pav",
    "Butter Baby Naan",
    "Butter Kulcha",
    "Butter Naan",
    "Chilli Naan",
    "Choor Choor Naan",
    "Fulka Roti",
    "Garlic Vulki Paratha",
    "Hariyali Naan",
    "Khandari Naan",
    "Kulcha",
    "Kulcha Naan",
    "Lachha Paratha",
    "Masala Puri",
    "Meduth Naan",
    "Methi Dhebra",
    "Mint Naan",
    "Missi Roti",
    "Paratha (plain)",
    "Plain Naan",
    "Poori",
    "Puran Puri",
    "Reshmi Paratha",
    "Rotla",
    "Rumali Roti",
    "Spinach Methi Paratha",
    "Stuffed Kulcha",
    "Stuffed Naan",
    "Stuffed Paratha",
    "Swami Roti",
    "Swamini Roti",
    "Tandoor Rotlo",
    "Tandoori Paratha",
    "Tandoori Roti",
    "Tawa Paratha",
    "Vulki Paratha"
  ]
},
{
  category: "Gujarati Curries",
  icon: "🍛",
  items: [
    "Aloo Dry Bhaji",
    "Bateta Nu Shaak",
    "Bhaji (Pav Bhaji)",
    "Bharelu Shaak",
    "Bhindi Corn Capsicum",
    "Bhindi Dahiwala",
    "Cashew Bitter Gourd",
    "Cashew Gathiya",
    "Cauliflower Peas",
    "Cauliflower Potato",
    "Chana Dal",
    "Chapdi Shaak",
    "Chole Chana",
    "Chole Churan",
    "Chori",
    "Desi Chana",
    "Dum Aloo",
    "Gathiya Onion",
    "Guvar Dhokli",
    "Kathol (Mixed Pulses)",
    "Methi Papad",
    "Methi Ringan",
    "Mix Vegetable",
    "Moong (Whole)",
    "Moong Beans",
    "Moth Beans",
    "Navratan Kathol",
    "Papdi Dana Muthiya",
    "Papdi Muthiya Ringan",
    "Patra Peas Corn",
    "Peanuts",
    "Panchratan Kathol",
    "Potato Corn Peas",
    "Potato Curry",
    "Potato Peas",
    "Rajma",
    "Rajma with Peanuts",
    "Rajwadi Dhokli",
    "Ringan no Oro",
    "Rimzim Aloo",
    "Sev Tomato Sabzi",
    "Split Green Gram Dal",
    "Steamed Vegetable (Varadiyu)",
    "Stuffed Bhindi with Chips",
    "Stuffed Brinjal Potato Mirch",
    "Stuffed Ladyfinger",
    "Surti Undhiyu (Green)",
    "Tawa Sabzi",
    "Turia Patra Peas",
    "Undhiyu",
    "Val Beans",
    "Vagharelu Rotlo",
    "White Chana",
    "White Chori"
  ]
},
{
  category: "Punjabi Curries",
  icon: "🍲",
  items: [
    "Aloo Dahiwala",
    "Aloo Gobi",
    "Aloo Matar",
    "Aloo Rajma",
    "Chana Masala",
    "Cheese Paneer Kalyani Roll",
    "Corn Capsicum Paneer",
    "Corn Capsicum Potato",
    "Corn Matar Mushroom",
    "Corn Methi Malai",
    "Diwani Handi",
    "Dum Aloo",
    "Jeera Aloo",
    "Khoya Kaju",
    "Malai Kofta",
    "Matar Methi Malai",
    "Methi Matar Masala",
    "Methi Paneer",
    "Mushroom Butter Masala",
    "Navratan Korma",
    "Palak Paneer",
    "Palak Paneer Bhurji",
    "Paneer Bhurji",
    "Paneer Butter Masala",
    "Paneer Darbari",
    "Paneer Handi",
    "Paneer Kali Mirch",
    "Paneer Kadai",
    "Paneer Khurchan",
    "Paneer Kofta",
    "Paneer Lababdar",
    "Paneer Lazeez",
    "Paneer Lajawab",
    "Paneer Mirch Ka Salan",
    "Paneer Mughlai",
    "Paneer Pasanda",
    "Paneer Patiala",
    "Paneer Reshmi",
    "Paneer Shahi Masala",
    "Paneer Takatak",
    "Paneer Tikka",
    "Paneer Tufani",
    "Rajasthani Gatta Curry",
    "Tawa Sabzi",
    "Tomato Corn Bhartha",
    "Veg Achari",
    "Veg Amritsari",
    "Veg Begum Bahar",
    "Veg Harabhara",
    "Veg Hariyali",
    "Veg Hungama",
    "Veg Jaipuri",
    "Veg Kalai Masala",
    "Veg Kolhapuri",
    "Veg Makhhanwala",
    "Veg Nawabi",
    "Veg Pahadi",
    "Veg Palak Kofta",
    "Veg Takatak",
    "Veg Takkarari",
    "Veg Tufani"
  ]
},
    {
  category: "Kathiyawadi Counter",
  icon: "🍲",
  items: [
    "Bajra Rotla",
    "Bhakhri",
    "Butter, Ghee, Jaggery",
    "Chaas",
    "Churma Ladoo",
    "Dabka Kadhi",
    "Dahi Khaman",
    "Dahi Tikhari",
    "Dal Dhokli",
    "Dessert",
    "Dhebra",
    "Dhokli Sabzi",
    "Garlic Chutney",
    "Green Olo",
    "Green Onions",
    "Hot Bhajiya",
    "Jowar Rotla",
    "Kadhi",
    "Khichdi",
    "Khichu",
    "Khichu Papad",
    "Lasaniya Bateta",
    "Masala Chaas",
    "Moong Dal",
    "Muthiya Dhokla",
    "Pickle",
    "Ringan no Olo",
    "Salad",
    "Sambharo",
    "Sev Tomato Sabzi",
    "Stuffed Brinjal & Potatoes",
    "Tempered Khichdi",
    "Tempered Rotla",
    "Thepla",
    "Urad Dal"
  ]
},
{
  category: "Farsan",
  icon: "🥟",
  items: [
    "African Roll",
    "Bhaji Dhokla",
    "Bhajiya",
    "Capsicum Rings",
    "Cheese Peas Samosa",
    "Chinese Samosa",
    "Coriander Kali",
    "Corn Marvel",
    "Dahi Khaman",
    "French Fries",
    "Fried Idli",
    "Ghughra",
    "Harabhara Roll",
    "Hungarian Potato",
    "Khaman",
    "Khandvi",
    "Khasta Kachori",
    "Moong Dal Kachori",
    "Paneer Cutlet",
    "Peas Kachori",
    "Peas Samosa",
    "Punjabi Samosa",
    "Rajdhani Roll",
    "Ras Patra",
    "Sabudana Vada",
    "Sandwich Dhokla",
    "Schezwan Balls",
    "Sesame Finger",
    "Sev Khaman",
    "Spanish Toss",
    "Spring Roll",
    "Steamed Dhokla",
    "Tawa Corn Roll",
    "Tawa Mehefil",
    "Tawa Patties",
    "Three-in-One Patties",
    "Veg Cutlet",
    "Veg Handvo",
    "Veg Muthiya Dhokla",
    "Veg Tikki",
    "Vibrant Gujarat Platter",
    "Wonton Samosa"
  ]
},
{
  category: "Chaat",
  icon: "🥣",
  items: [
    "Agra ke Bhalla",
    "Aloo Chaat",
    "Aloo Matar Chaat",
    "Aloo Tikki",
    "Banarasi Chaat",
    "Basket Chaat",
    "Besan Poodla",
    "Bhel",
    "Bhel Puri",
    "Bhalla Chaat",
    "Birdhawan Tikki Chaat",
    "Chaat",
    "Chana Chaat",
    "Chatpati Idli",
    "Chole Tikki",
    "Coconut Chaat",
    "Corn Papdi Chaat",
    "Dahi Bhalla",
    "Dahi Chaat",
    "Dahi Gunjiya",
    "Dahi Kachori",
    "Delhi Chaat",
    "Diamond Chaat",
    "Indori Chaat",
    "Jodhpuri Chaat",
    "Kalmi Chaat",
    "Kolkata Chaat",
    "Lucknowi Chaat",
    "Mango Dahi Vada (Seasonal)",
    "Matka Dahi Vada",
    "Mexican Tikki Chaat",
    "Mexican Tikki Ragda",
    "Orange Papdi Chaat",
    "Palak Chaat",
    "Paneer Chilla",
    "Paneer Saute",
    "Pani Puri",
    "Papdi Chaat",
    "Ponk Chilla",
    "Ragda Pattice",
    "Raj Kachori",
    "Rajbhog Chaat",
    "Rajdhani Chaat",
    "Rimzim Chaat",
    "Saunth ki Tikkiya",
    "Samosa Chaat",
    "Tawa Mathura Chaat"
  ]
},
{
  category: "Pizza & Toast",
  icon: "🍕",
  items: [
    "Baby Pizza",
    "Bread Pizza",
    "Busatta",
    "Cheese Focaccia Bread",
    "Couple Crunchy",
    "Garlic Bread",
    "Indian Touch Pizza",
    "Italian Cruise",
    "Italian Kulcha",
    "Italian Pizza",
    "Italian Volvo",
    "Jhatpat Spicy",
    "Khari Pizza",
    "Masala Grill Sandwich",
    "Mexican Pizza",
    "Pineapple Pizza",
    "Pocket Pizza",
    "Russian Cheese Toast",
    "Russian Grill",
    "Taco",
    "Thin Crust Pizza",
    "Titbit",
    "Veg Pizza"
  ]
},
{
  category: "South Indian",
  icon: "🍛",
  items: [
    "Cheese Dosa",
    "Chutney",
    "Coconut Curry",
    "Dosa (3 Types)",
    "Dosa (Soya / Jodhpuri)",
    "Idli",
    "Jini Dosa",
    "Lava Idli",
    "Masala Dosa",
    "Medu Vada",
    "Mixed Vegetable Uttapam",
    "Mysore Masala Dosa",
    "Onion Uttapam",
    "Pal Appam",
    "Paper Dosa",
    "Payasam",
    "Plain Dosa",
    "Rasam",
    "Sambar",
    "Sandwich Uttapam",
    "Schezwan Idli",
    "Tandoori Idli",
    "Thatte Idli",
    "Tomato Uttapam",
    "Upma"
  ]
},
{
  category: "Italian & Mexican",
  icon: "🌮",
  items: [
    "Alfredo Sauce",
    "Arrabbiata Sauce",
    "Bean & Veg Burritos",
    "Burrito Bowls",
    "Caroline Pasta",
    "Cheese Burritos",
    "Cheese Lasagna",
    "Enchiladas",
    "Garlic Bread",
    "Guacamole + Salsa",
    "Italian Sizzler",
    "Loaded Nachos",
    "Mexican Cassata",
    "Mexican Corn Cups",
    "Mexican Quesadilla",
    "Mexican Rice (Veg)",
    "Mexican Salad",
    "Panini",
    "Paneer Tacos",
    "Pesto Sauce",
    "Pizza (Live Counter with Toppings)",
    "Tacos",
    "Veg Burritos",
    "Veg Sizzler"
  ]
},
{
  category: "Chinese Menu",
  icon: "🍜",
  items: [
    "American Cheese Toast",
    "American Wonton",
    "Baby Corn Manchurian",
    "Chinese Bhel",
    "Chinese Cola",
    "Chinese Pasta Loot",
    "Chini Changa",
    "Crispy Baby Corn",
    "Dragon Potato",
    "Dry Manchurian",
    "Finger Chips with Sauce",
    "Fried Rice",
    "Gobi Manchurian",
    "Hakka Noodles",
    "Honey Chilli Potato",
    "Lazy Fry",
    "Paneer Chilli",
    "Red White Pasta",
    "Schezwan Noodles",
    "Sesame Rolls",
    "Spring Roll",
    "Triple Schezwan Rice",
    "Veg Crispy",
    "Veg Manchurian",
    "Veg Noodles",
    "Veg Schezwan Fried Rice"
  ]
},
{
  category: "Live Snacks Counter",
  icon: "🥟",
  items: [
    "Aloo Tikki",
    "Bread Pakoda",
    "Bread Rolls",
    "Burger",
    "Cheese Corn Cutlet",
    "Cheese Garlic Bread",
    "Chole Bhature",
    "Dabeli",
    "Dal Vada",
    "Focaccia",
    "Frankie",
    "French Fries",
    "Handvo",
    "Hungarian Potato",
    "Kachori Pizza",
    "Khichu",
    "Masala Fries",
    "Methi Na Gota",
    "Mini Dosa",
    "Mini Pizza",
    "Paneer Pakoda",
    "Paneer Roll",
    "Patra",
    "Pav Bhaji",
    "Pani Puri",
    "Pizza Dhokla",
    "Ragda Pattice",
    "Rajwadi Bhajiya",
    "Samosa",
    "Sev Khamani",
    "Spinach Dhokla",
    "Spring Dosa",
    "Steamed Dhokla",
    "Uttariya + Chutney",
    "Vada Pav",
    "Veg Wrap"
  ]
},
    {
  category: "Dal & Rice",
  icon: "🍚",
  items: [
    "Centro Rice (Thai Curry)",
    "Crud",
    "Dal",
    "Dal Dhabha Style",
    "Dal Fry",
    "Dal Makhani",
    "Dal Tadka (Live)",
    "Dry Fruit Pulao",
    "Dum Biryani",
    "Gujarati Kadhi",
    "Gujarati Khichdi",
    "Hyderabadi Biryani",
    "Hyderabadi Dal",
    "Jeera Rice",
    "Jodhpuri Pulao",
    "Kesar Pulao",
    "Lemon Coriander Rice",
    "Malaysian Rice",
    "Matar Pulao",
    "Mexican Rice",
    "Moong Dal",
    "Nawabi Takarari Biryani",
    "Panchratna Dal",
    "Palak Corn Rice",
    "Peas Pulao",
    "Plain Rice",
    "Rajasthani Kadhi",
    "Rajasthani Khichiya",
    "Rajasthani Moong Dal",
    "Steam Rice",
    "Tawa Biryani",
    "Urad Dal",
    "Veg Biryani",
    "Veg Pulao"
  ]
},
{
  category: "Salads",
  icon: "🥗",
  items: [
    "Almond Salad",
    "American Corn Salad",
    "Bean Salad",
    "Boondi Raita",
    "Chinese Apple Salad",
    "Coconut Raita",
    "Cone Cream Bean Salad",
    "Cream Potato with Herbs",
    "Farsan Salad",
    "Fransevell Dekong",
    "Fruit & Bean Salad",
    "Fruit Pineapple Raita",
    "Fruit Raita",
    "Fried Green Chilies",
    "Fusilli Pasta Salad",
    "German Potato Salad",
    "Green Salad",
    "Kab Salad",
    "Mediterranean Bean Salad",
    "Onion",
    "Pako Sambhar",
    "Pasta Salad",
    "Peanut Coconut Salad",
    "Pickle Salad",
    "Pineapple Apple Salad",
    "Pineapple Raita",
    "Russian Salad",
    "Salad",
    "Salad Counter",
    "Sambharo",
    "Sundari Bhindi",
    "Vegetable Raita"
  ]
},
{
  category: "Papad, Chutney & Pickles",
  icon: "🥣",
  items: [
    "Churi Papad",
    "Coconut Chutney",
    "Disco Papad",
    "Fruit Chutney",
    "Fry Papad",
    "Fryums",
    "Garlic Chutney",
    "Green Chutney",
    "Gujarati Pickle",
    "Gunda Pickle",
    "Kadhi Mirchi",
    "Kutchi Chutney",
    "Mango Methiya",
    "Papad",
    "Punjabi Pickle",
    "Raw Mango & Grapes",
    "Red Chutney",
    "Roasted Papad",
    "Stuffed Chillies",
    "Yogurt Chutney"
  ]
},
{
  category: "Buttermilk",
  icon: "🥛",
  items: [
    "Dahi",
    "Makhan",
    "Masala Buttermilk",
    "Plain Buttermilk"
  ]
},
{
  category: "Water",
  icon: "💧",
  items: [
    "Water Bottle",
    "Water Jug"
  ]
},
{
  category: "Desserts",
  icon: "🍰",
  items: [
    "Candy",
    "Chocolate Brownie",
    "Espresso Coffee",
    "Fanta",
    "Fruit Dish",
    "Gola",
    "Hot Brownie Sizzler",
    "Hot Gulab Jamun",
    "Ice Cream",
    "Lemon Soda",
    "Mango Juice",
    "Pan with Poetry",
    "Rajwadi Mukhwas",
    "Raspberry Jalebi",
    "Saffron Jalebi",
    "Salted Peanuts (Khari Sing)",
    "Sprite",
    "Sugarcane Juice",
    "Tea",
    "Thums Up",
    "Vimto"
  ]
},
{
  category: "Morning Breakfast",
  icon: "🍳",
  items: [
    "Aloo Paratha",
    "Assorted Namkeen",
    "Bhakri",
    "Bhel",
    "Bread Butter",
    "Chillies – Raita Chillies",
    "Chips",
    "Chutney",
    "Curd",
    "Dal Pakwan",
    "Dhebra",
    "Exclusive Bakery Counter",
    "Fafda Gathiya",
    "Fried Green Chilies",
    "Fresh Fruit / Juice",
    "Grilled Sandwich",
    "Indori Poha",
    "Khajli",
    "Khakhra",
    "Khari Sing",
    "Medu Vada",
    "Milk / Tea / Coffee",
    "Moong Shaak",
    "Poha",
    "Saffron Jalebi",
    "Sauce – Chutney",
    "Sev Khamani",
    "Sambharo",
    "Sprouts",
    "Steam Idli",
    "Stuffed Paratha with Curd",
    "Tea",
    "Tea–Coffee",
    "Thepla",
    "Upma",
    "Uttapam",
    "Veg Cutlet",
    "White Dhokla"
  ]
},
{
  category: "Sanjhi Nasto",
  icon: "🥘",
  items: [
    "Assorted Namkeen",
    "Bhakhri",
    "Chinese Bhel",
    "Cold Drinks",
    "Dabeli",
    "Exclusive Bakery Counter",
    "French Fries",
    "Fresh Fruit / Fruit Juice",
    "Gathiya",
    "Khakhra",
    "Khari Sing (Salted Peanuts)",
    "Masala Corn",
    "Moong Sabzi",
    "Pani Puri",
    "Pav Bhaji",
    "Popcorn",
    "Ragda Pav",
    "Sandwich",
    "Schezwan Idli",
    "Simple Bhel",
    "Sauces & Chutneys",
    "Sprouts",
    "Thepla"
  ]
}
];
