# Generated by Django 6.0 on 2026-01-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0003_member_memberlog_delete_staffmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringevent',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cateringevent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cateringevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='cateringevent',
            name='venue',
            field=models.CharField(default='Not Specified', max_length=200),
        ),
        migrations.AlterField(
            model_name='cateringevent',
            name='event_type',
            field=models.CharField(max_length=100),
        ),
    ]
