# Generated by Django 6.0 on 2026-01-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0004_cateringevent_alternate_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringevent',
            name='menu_items',
            field=models.ManyToManyField(blank=True, related_name='events', to='catering.menu_item'),
        ),
    ]
