# Generated by Django 6.0 on 2026-01-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0005_cateringevent_menu_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gujarati_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
