# Generated by Django 6.0 on 2026-01-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0006_category_gujarati_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_item',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='menu_item',
            name='descp',
        ),
        migrations.AddField(
            model_name='menu_item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu_item',
            name='gujarati_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
