# Generated by Django 6.0 on 2026-01-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0014_cateringevent_advance_amount_cateringevent_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_user.png', upload_to='profile_images/'),
        ),
    ]
