# Generated by Django 6.0 on 2026-01-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0015_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
