# Generated by Django 6.0 on 2026-05-27 11:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0016_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringevent',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cateringevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cateringevent',
            name='event_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cateringevent',
            name='internal_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cateringevent',
            name='notes_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cateringevent',
            name='notes_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cateringevent',
            name='tracking_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='menu_item',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menu_item',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated tags e.g. wedding,starter,paneer', max_length=500),
        ),
        migrations.AlterField(
            model_name='cateringevent',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('manager', 'Manager'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
        migrations.CreateModel(
            name='EventStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('head_chef', 'Head Chef'), ('sous_chef', 'Sous Chef'), ('server', 'Server'), ('coordinator', 'Coordinator'), ('driver', 'Driver')], default='server', max_length=20)),
                ('confirmed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='catering.cateringevent')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Event Staff',
                'unique_together': {('event', 'member')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=10)),
                ('arrived_at', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('event_staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='catering.eventstaff')),
            ],
            options={
                'verbose_name_plural': 'Attendance Records',
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('wedding', 'Wedding'), ('corporate', 'Corporate'), ('birthday', 'Birthday'), ('food', 'Food'), ('setup', 'Setup'), ('other', 'Other')], default='other', max_length=50)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('cloudinary_url', models.URLField(blank=True, default='', max_length=500)),
                ('youtube_url', models.URLField(blank=True, default='', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_count', models.IntegerField(default=0)),
                ('profit_margin_pct', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('seasonal_peak', models.CharField(blank=True, default='', help_text='Comma-separated month numbers, e.g. "11,12,1,2"', max_length=50)),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='catering.menu_item')),
            ],
            options={
                'verbose_name_plural': 'Menu Item Stats',
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('deadline', models.DateField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['deadline', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_new_ip', models.BooleanField(default=False)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Login Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('3day', '3 Days Before'), ('1day', '1 Day Before')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='catering.cateringevent')),
            ],
            options={
                'unique_together': {('event', 'reminder_type')},
            },
        ),
        migrations.CreateModel(
            name='ItemCoOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('item_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooccurrence_a', to='catering.menu_item')),
                ('item_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooccurrence_b', to='catering.menu_item')),
            ],
            options={
                'verbose_name_plural': 'Item Co-Occurrences',
                'unique_together': {('item_a', 'item_b')},
            },
        ),
    ]
