# Generated by Django 6.0 on 2026-05-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0023_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='related_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='related_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='related_type',
            field=models.CharField(blank=True, choices=[('event', 'Event'), ('menu', 'Menu'), ('booking', 'Booking'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
