# Generated by Django 6.0 on 2026-05-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0024_activitylog_related_date_activitylog_related_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='custom_items_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
